### ISSUE TITLE
crash with XaeroWorldMap 1.30.3 Fabric 1.19.3

### ISSUE THREAD

**Issue by ewe2** [Entropy5/JMtoXaero#8]
`java -jar JMtoXaero-2.2.jar "MultiMC/instances/1.19.31/.minecraft/journeymap/data/sp/" "MultiMC/instances/1.19.31/.minecraft/XaeroWorldMap/New World" all

Processing dimension -1                            

Exception in thread "main" java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:208)
        at com.github.entropy5.JourneyMapToXaero.processDimension(JourneyMapToXaero.java:136)
        at com.github.entropy5.JourneyMapToXaero.main(JourneyMapToXaero.java:51)`

I'm using java 17 on a debian linux box, I tested java 11 to rule out a java incompatibility but it was the same error. Also tested overworld dimension 0 on its own, same result. It isn't creating folders under  XaeroWorldMap. Version of journeymap is 1.19.3-5.9.2 fabric.

**Comment by Entropy5** [comment]
I made this for version 1.12
For later versions of journeymap, they changed the names of the folders, so this program isnt finding them
You can change them to what they are in 1.12, as i show in the video guide, and then it should work

overworld to DIM0
nether to DIM-1
end to DIM1

**Comment by ewe2** [comment]
I changed the Journeymap directory as you suggested (I only have overworld) and fixed a mistake I'd made with the input directory and it processed it but processed the directory as null not DIM0 and did not copy any waypoints but did remap the other journeymap data.

**Comment by Entropy5** [comment]
in xaeros 1.12 the overworld directory is called null, for some reason
im not sure if that is still the case in higher versions, but you can rename it
my tool doesnt do waypoints
https://github.com/rfresh2/JMWaypointsToXaero
